project:
  type: website
  output-dir: docs

website:
  title: "Anthony Luna"
  search:
    location: navbar
  navbar:
    pinned: true
    background: white
    right:
      - text: "About Anthony"
        href: about.qmd
format:
  html:
    mainfont: "Fira Code"
    monofont: "Fira Code"
    page-layout: article
    include-in-header: 
      - header.html
    css: styles.scss


